#In this notebook, we're going to cover some of the most fundamentals concepts of tensor using tensorflow

More specifically, we're going to cover:
* Introduction to tensors
* Getting information from tensors
* Manipulating tensors
* Tensors & Numpy
* Using @tf.function(a way to speed up our regular python functions)
* Using GPUs with tenserflow
* Exercises to try for ourselves


## Introduction to Tensors

In [ ]:
# import Tensorflow
import tensorflow as tf
print(tf.__version__)

2.5.0


In [ ]:
# Creating tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
# Check the number of dimension of a tensor (ndim stands for number of dimensions)
scalar.ndim

0

In [ ]:
# Create a vector
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
# Check the dimension of our vector
vector.ndim


1

In [ ]:
# Check the matrix (has more than  1 dimension)
matrix = tf.constant([[10, 7], [7, 10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [ ]:
matrix.ndim

2

In [ ]:
# Create another matrix
another_matrix = tf.constant([[10., 7],
                              [3., 2],
                              [8., 9]], dtype = tf.float16) # specify the data type with dtype parameter
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [ ]:
# What's the number dimensions of another_matrix?
another_matrix.ndim

2

In [ ]:
# Let's create a tensor
tensor = tf.constant([[[1, 2, 3],
                       [4, 5, 6]],
                       [[7, 8, 9],
                       [10, 11, 12]],
                       [[13, 14, 15],
                       [16, 17, 18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [ ]:
tensor.ndim

3

What we've created so far
* Scalar: a single number
* Vector: a number with dimension (e.g. wind speed and direction)
* Matrix: a 2-dimensional array of numbers
* Tensor: an n-dimensional array of numbers (when n can be any number, 0-dimensional tensor is a scalar, a 1-dimensional tensor is a vector)

### Creating tensors with `tf.Variable`

In [ ]:
tf.Variable

tensorflow.python.ops.variables.Variable

In [ ]:
# Create the samme tensor with tf.Variable() as above
changeable_tensor = tf.Variable([10, 7])
unchangeable_tensor = tf.constant([10, 7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [ ]:
 # Let's try change one of the elements in our changeable tensor
 changeable_tensor[0].assign(7)
 changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [ ]:
# Let's try change our unchangeable tensor
unchangeable_tensor[0].assign(7)
unchangeable_tensor

AttributeError: ignored

### **Note**: Rarely need in practice if we need to decide wheather to use `tf.constant` or `tf.Variable` to create tensors, as TensorFlow does this for us. However, if in doubt, use `tf.constant` and change it ater if needed.

## Creating Random Tensors
Radom tensors are tensors of same abitrary size which contain rndom numbers

In [ ]:
# Create two random but the same tensors
random_1 = tf.random.Generator.from_seed(7) # set seed for reproducibility
random_1 = random_1.normal(shape=(3, 2))
random_2 = tf.random.Generator.from_seed(7)
random_2 = random_2.normal(shape=(3, 2))

# Are they equal?
random_1, random_2, random_1 == random_2

### Shuffle the orders of elements in a Tensor

In [ ]:
# Shuffle a tensor (valuable for when we want to shuffle our data so the inherent order doesn't effect learning)
not_shuffled = tf.constant([[10, 7],
                            [3, 4],
                            [2, 5]])
not_shuffled.ndim

# Shuffle our Non-shuffled tensor
tf.random.shuffle(not_shuffled)

In [ ]:
# Shuffle our Non-shuffled tensor
tf.random.set_seed(42)
tf.random.shuffle(not_shuffled, seed = 42)

**Exercise**: Read through TensorFlow documentation on random seed generation:
https://www.tensorflow.org/api_docs/python/tf/random/set_seed and practice writing some random tensors and shuffle them

It looks like if we want our shuffled tensors to be in the sae order, we've got to use the global level random seed as well as the operation level random seed:

> Rule 4: "If both the global and the operational seeds are set: Both seeds are used in conjuction to determine the random sequence."

In [ ]:
tf.random.set_seed(42) # gobal level random seed
tf.random.shuffle(not_shuffled, seed = 42) # Operation level random seed

### Other ways to make Tensors

In [ ]:
# Create the tensors for all ones
tf.ones([10, 7])

In [ ]:
# Create the tensors for all zeros
tf.zeros(shape=(3, 4))


### Turn Numpy arrays into tensors

The main difference between NumPy and TensoFlow is that Tensors can be run on GPU (much faster than Numerical computing).

In [ ]:
# We can also numpy arrays into tensors 
import numpy as np
numpy_A = np.arange(1, 25, dtype= np.int32) # Create a NumPy array between 1 and 25
numpy_A

# x = tf.constant(some_matrix) # Capital for matrix or tensor
# y = tf.constant(vector) # Non-Capital for vector

In [ ]:
A = tf.constant(numpy_A, shape=(3, 8))
B = tf.constant(numpy_A)
A, B

In [ ]:
3 * 8

In [ ]:
A.ndim

# Gettng information on Tensors 

When dealing with Tensors we probably want to be aware of the following attributs:
 
* Rank
* Shape
* Axis or dimensions
* Size

In [ ]:
# Create rank 4 tensor ( 4 dimensions )
rank_4_tensor = tf.zeros(shape = [2, 3, 4, 5])
rank_4_tensor

In [ ]:
rank_4_tensor[0]

In [ ]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

In [ ]:
# Get various attributes of our tensors
print("Datatype of every element: ", rank_4_tensor.dtype)
print("Number of dimensions (rank): ", rank_4_tensor.ndim)
print("Shape of Tensors: ", rank_4_tensor.shape)
print("Elements along the  0 axis: ", rank_4_tensor.shape[0])
print("Elements along the  last axis: ", rank_4_tensor.shape[-1])
print("Total number of elements in our tensor: ", tf.size(rank_4_tensor))
print("Total number of elements in our tensor: ", tf.size(rank_4_tensor).numpy())

### Indexing Tensors 

Tensors can be index just like python lists

In [ ]:
some_list = [1, 2, 3, 4]
some_list[:2]

In [ ]:
# Get the first 2 elements of each dimensions
rank_4_tensor[:2, :2, :2, :2]


In [ ]:
# Get the first element from each dimension from each index except for the final one
rank_4_tensor[:1, :1, :1, :]

In [ ]:
# Create a rank 2 tensor ( 2 dimensions )
rank_2_tensor = tf.constant([[20, 7],
                             [2, 3]])
rank_2_tensor.shape, rank_2_tensor.ndim

In [ ]:
rank_2_tensor

In [ ]:
# Get the last item of each of row of our rank 2 tensor
rank_2_tensor[:, -1]

In [ ]:
# Add in extra dimension to our rank 2 tensor
rank_3_tensor = rank_2_tensor[..., tf.newaxis]
rank_3_tensor

In [ ]:
# Alternative to the tf.newaxis
tf.expand_dims(rank_2_tensor, axis=0) # "-1" means expands the final axis

In [ ]:
# Exapnd the 0 axis
tf.expand_dims(rank_2_tensor, axis=0)

In [ ]:
rank_2_tensor

### Manipulating tensors (tensors operations) 

**Basics Operations**
`+`, `-`,`*`,`/`

In [ ]:
# We can add values to a tensor using the addition operator
tensor = tf.constant([[10, 7], [3, 4]])
tensor + 10

In [ ]:
# Original tensor is unchanged
tensor

In [ ]:
# Multiplication also works
tensor * 10

In [ ]:
# Substraction if we want
tensor - 10

In [ ]:
# We can use the tensorflow built-in function
tf.multiply(tensor, 10)

**Matrix Multiplication**

In Machine Learning, matrix multiplication is one of the common tensor operations.

There are two rules our tensors (or matrices) need to fulfil if we're going to matrix multiply items:

1. The inner dimensions must match
2. The resulting ,atrix has the shape of outer dimensions 

In [ ]:
# Matrix multiplication in TensorFlow
print(tensor)
tf.matmul(tensor, tensor)

In [ ]:
tensor, tensor

In [ ]:
tensor * tensor

In [ ]:
# Matrix multiplication with Python operator "@"
tensor @ tensor

In [ ]:
# Create a tensor (3, 2) 
X = tf.constant([[1, 2],
                 [3, 4],
                 [5, 6]])
# Create another tensor (3, 2) tensor
Y = tf.constant([[7, 8],
                 [9, 10],
                 [11, 12]])
X, Y

In [ ]:
# Try to matrix multiply tensors of same shape
tf.mulmat(X, Y)

In [ ]:
Y

In [ ]:
# Let's change the shape of Y
tf.reshape(Y, shape=(2, 3))

**Resource**: Info and example of matrix multiplication: https://www.mathsisfun.com/algebra/matrix-multiplying.html

In [ ]:
# Try to matrix multiply X by reshaped Y
X @ tf.reshape(Y, shape=(2, 3))

In [ ]:
tf.matmul(X, tf.reshape(Y, shape=(2, 3)))

In [ ]:
tf.reshape(X, shape=(2, 3)).shape, Y.shape

In [ ]:
# Try change the shape X instead of Y
tf.matmul(tf.reshape(X, shape=(2, 3)), Y)

In [ ]:
# Can do the same with transpose
tf.transpose(X), tf.reshape(X, shape=(2, 3))


In [ ]:
# Try matrix multiplication with transpose rather than reshape
tf.matmul(tf.transpose(X), Y)

 **The Dot Product**

 Matrix multiplication is also referred to as the dot product.

 We can perform matrix multiplication using:
 * `tf.matmul()`
 * `tf.tensordot()`
 * `@`

In [ ]:
# Perform the dot product on X and Y (requires X or Y to be transposed)
tf.tensordot(tf.transpose(X), Y, axes=1)

In [ ]:
# Perform matrix multiplication between X and Y (transposed)
tf.matmul(X, tf.transpose(Y))

In [ ]:
# Perform matrix multipication between X and Y (reshaped)
tf.matmul(X, tf.reshape(Y, shape=(2, 3)))

In [ ]:
# Check the values of Y, reshape Y and transposed Y
print("Normal Y: ")
print(Y, "\n")

print("Y reshaped: ")
print(tf.reshape(Y, (2, 3)), "\n")

print("Y transposed: ")
print(tf.transpose(Y))

In [ ]:
tf.matmul(X, tf.transpose(Y))

Generally, when performing matrix multiplication on two tensors and one of the axes doesn't line up, we will transpose (rather than reshape) one of the tensors get satisfy the matrix multiplication rules.

### Changing the datatype of a tensors

In [ ]:
# Create a new tensor with default datatype (float32)
B = tf.constant([1.7, 7.4])
B.dtype

In [ ]:
C = tf.constant([7, 10])
C, C.dtype

In [ ]:
# Change from float32 to float16
D = tf.cast(B, dtype=tf.float16)
D, D.dtype

In [ ]:
# Change from int32 to float32
E = tf.cast(C, dtype=tf.float32)
E

In [ ]:
E_float16 = tf.cast(C, dtype=tf.float32)
E

### Aggregating tensors

Aggregrating tensors = condensing them from multiple values down to a smaller amount of values.

In [ ]:
# Get the absolute values
D = tf.constant([-7, -10])
D

In [ ]:
# Get the absollute values
tf.abs(D)

Let's go through the following forms of aggregation:

* Get the minimum
* Get the maximum
* Get the mean of a tensor
* Get the sum of tensor

In [ ]:
# Creating a random tensor with values between 0 and 100 of size 50
import numpy as np
E = tf.constant(np.random.randint(0, 100, size = 50))
E

In [ ]:
tf.size(E), E.shape, E.ndim

In [ ]:
# Find the minimum
tf.reduce_min(E)

In [ ]:
# Find the maximum
tf.reduce_max(E)

NameError: ignored

In [ ]:
# Find the mean
tf.reduce_mean(E)

In [ ]:
# Find the sum
tf.reduce_sum(E)

In [ ]:
E

**Exercise**: With what we've just learned, find the variance and standard deviation of our "E" tensor using TensorFlow methods.

In [ ]:
# FInd the variance of our tensor
tf.math.reduce_variance()  # won't work

TypeError: ignored

In [ ]:
# To find the variance of our tensor, we need access to tensorflow_probability 
import tensorflow_probability as tfp
tfp.stats.variance(E)

In [ ]:
# FInd the standard deviation
tf.math.reduce_variance(tf.cast(E, dtype=tf.float32))

### Find the positional maximum and minimum



In [ ]:
# Create a new tensor for finding positional minimum and maximum
tf.random.set_seed(42)
F = tf.random.uniform(shape=[50])
F

In [ ]:
# Find the positional maximum
tf.argmax(F)

In [ ]:
# Index on our largest value position
F[tf.argmax(F)]

In [ ]:
# Find the maximum value of F
tf.reduce_max(F)

In [ ]:
# Check for equality
F[tf.argmax(F)] == tf.reduce_max(F)

NameError: ignored

In [ ]:
# Find the positional minimum
tf.argmin(F) 

In [ ]:
# Find the minimum using the positional minimum index
F[tf.argmin(F)]

### Squeezing a tensor (removing all singke dimensions)

In [ ]:
# Create a tensor to get started
G = tf.constant(tf.random.uniform(shape=[50]), shape=(1, 1, 1, 1, 50))
G

In [ ]:
G.shape

In [ ]:
G_squeezed = tf.squeeze(G)
G_squeezed, G_squeezed.shape

### One-hot encoding tensors

In [ ]:
# Create the list of indices 
some_list = [0, 1, 2, 3]

# One-hot encode our list of inices
tf.one_hot(some_list, depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [ ]:
# Specify custom values for one hot encoding
tf.one_hot(some_list, depth=4, on_value="Hey myself soumy ", off_value="I also like to play instruments")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'Hey myself soumy ', b'I also like to play instruments',
        b'I also like to play instruments',
        b'I also like to play instruments'],
       [b'I also like to play instruments', b'Hey myself soumy ',
        b'I also like to play instruments',
        b'I also like to play instruments'],
       [b'I also like to play instruments',
        b'I also like to play instruments', b'Hey myself soumy ',
        b'I also like to play instruments'],
       [b'I also like to play instruments',
        b'I also like to play instruments',
        b'I also like to play instruments', b'Hey myself soumy ']],
      dtype=object)>

### Squaring, log, square root

In [ ]:
# Create a new tensor
H = tf.range(1, 10)
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [ ]:
# Square it 
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [ ]:
# Find the squareroot
tf.sqrt(tf.cast(H, dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.99999994, 1.4142134 , 1.7320508 , 1.9999999 , 2.236068  ,
       2.4494896 , 2.6457512 , 2.8284268 , 3.        ], dtype=float32)>

In [ ]:
# Find the log
tf.math.log(tf.cast(H, dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

### Tensors and NumPy

TensorFlow interacts beautfully with NumPy arrays:

**Note:** One of the main differences between a TensorFlow tensor and a NumPy array is that a TensorFlow tensor can be run on a GPU and TPU (for faster numerical processing)

In [ ]:
# Create a tensor directly from NumPy arrays
import numpy as np
J = tf.constant(np.array([3., 7., 10.]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [ ]:
# Convert our tensor back to a NumPy arrays
np.array(J), type(np.array(J))

(array([ 3.,  7., 10.]), numpy.ndarray)

In [ ]:
# Convert tensor J to a NumPy array
J.numpy(), type(J.numpy())

(array([ 3.,  7., 10.]), numpy.ndarray)

In [ ]:
J = tf.constant([3.])
J.numpy()[0]

3.0

In [ ]:
# The default types of each are slighty different
numpy_J = tf.constant(np.array([3., 7., 10.]))
tensor_J = tf.constant([3., 7., 10.])

# Check the datatypes of each
numpy_J.dtype, tensor_J.dtype

(tf.float64, tf.float32)

### Finding access to GPUs

In [ ]:
import tensorflow as tf
tf.config.list_physical_devices("GPU")

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [ ]:
!nvidia-smi

Sat May 29 15:56:00 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 465.19.01    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   37C    P8     9W /  70W |      3MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

> **Note**: If you have access to a CUDA-enabled GPU, TensorFlow will automatically use it whenever possible 